// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AccountDropdown: typeof import('./components/AccountDropdown.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    ClientForm: typeof import('./components/forms/ClientForm.vue')['default']
    ClientModal: typeof import('./components/ClientModal.vue')['default']
    ClientRow: typeof import('./components/ClientRow.vue')['default']
    EventCard: typeof import('./components/EventCard.vue')['default']
    EventModal: typeof import('./components/EventModal.vue')['default']
    Field: typeof import('./components/forms/Field.vue')['default']
    FreeTimeline: typeof import('./components/FreeTimeline.vue')['default']
    'Iconoir:addUser': typeof import('~icons/iconoir/add-user')['default']
    'Iconoir:alignCenter': typeof import('~icons/iconoir/align-center')['default']
    'Iconoir:alignJustify': typeof import('~icons/iconoir/align-justify')['default']
    'Iconoir:alignLeft': typeof import('~icons/iconoir/align-left')['default']
    'Iconoir:alignRight': typeof import('~icons/iconoir/align-right')['default']
    'Iconoir:calendar': typeof import('~icons/iconoir/calendar')['default']
    'Iconoir:menu': typeof import('~icons/iconoir/menu')['default']
    IconoirArrowRight: typeof import('~icons/iconoir/arrow-right')['default']
    'IconParkOutline:close': typeof import('~icons/icon-park-outline/close')['default']
    LoginForm: typeof import('./components/forms/LoginForm.vue')['default']
    'Logos:googleIcon': typeof import('~icons/logos/google-icon')['default']
    'Majesticons:dotsVerticalLine': typeof import('~icons/majesticons/dots-vertical-line')['default']
    'Mdi:greasePencil': typeof import('~icons/mdi/grease-pencil')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    'Ph:star': typeof import('~icons/ph/star')['default']
    'Ph:starFill': typeof import('~icons/ph/star-fill')['default']
    QuickEventForm: typeof import('./components/forms/QuickEventForm.vue')['default']
    README: typeof import('./components/README.md')['default']
    RegisterForm: typeof import('./components/forms/RegisterForm.vue')['default']
    SelectField: typeof import('./components/forms/SelectField.vue')['default']
    TextEditor: typeof import('./components/TextEditor.vue')['default']
    ToolCard: typeof import('./components/ToolCard.vue')['default']
    ToolForm: typeof import('./components/forms/ToolForm.vue')['default']
  }
}

export { }
